name: Release update

on:
  push:
  workflow_dispatch:
    inputs:
      prerelease:
        description: Prerelease
        type: boolean
        required: false

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
      - name: Build release APK
        run: |
          chmod +x ./gradlew
          ./gradlew clean assembleLawnWithQuickstepGithubRelease
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release APK
          path: build/outputs/apk